title: Ma page personnel
author: Centon21
email: tisoumine97474@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ceci est un test 
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
